name: grobid_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - requests
  - pandas
  - wordcloud
  - numpy
  - matplotlib
  - pip:
      - beautifulsoup4
      - certifi
      - pillow
      - pyparsing
      - python-dateutil
      - pytz
      - tqdm
